In [1]:
import pandas as pd

In [2]:
epi = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/epi_articles_2023_2025.csv")
fed = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/fed_news_resources.csv")
fft = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/fft_education_datalab_blog.csv")
gov = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/govuk_dfe_articles_2023_2025.csv")
nuffield = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/nuffield_articles_2023_2025.csv")
schoolsweek = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/schoolsweek_articles_2023_2025.csv")

In [3]:
schoolsweek.head()

,url,title,date,text
0,https://schoolsweek.co.uk/schools-lack-resourc...,Schools lack resources to keep pupils with SEN...,2025-12-11 05:00,Schools lack resources needed to help keep chi...
1,https://schoolsweek.co.uk/nightmare-before-chr...,‘Nightmare before Christmas’: 46 free school p...,2025-12-11 22:30,Twenty-eight mainstream and 18 special free sc...
2,https://schoolsweek.co.uk/russell-hobby-to-bec...,Russell Hobby to become Labour peer – but will...,2025-12-10 17:25,Academy CEO and former NAHT general secretaryR...
3,https://schoolsweek.co.uk/dfe-dodges-data-tran...,DfE dodges data transparency as it plans new p...,2025-12-08 05:00,The Department for Education (DfE) has refused...
4,https://schoolsweek.co.uk/ofsted-should-check-...,Ofsted should check SEND funding not plugging ...,2025-12-12 09:00,School governing boards are urging Ofsted to e...

In [4]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

📄 EPI
Rows: 115
Columns: ['url', 'title', 'date', 'text']

📄 FED
Rows: 106
Columns: ['url', 'title', 'date', 'text']

📄 FFT
Rows: 202
Columns: ['url', 'title', 'date', 'text']

📄 GOV
Rows: 1061
Columns: ['url', 'title', 'from', 'date', 'text']

📄 NUFFIELD
Rows: 107
Columns: ['url', 'title', 'date', 'text']

📄 SCHOOLSWEEK
Rows: 2742
Columns: ['url', 'title', 'date', 'text']

In [5]:
epi["from"] = "epi"
epi["type"] = "think_tank"

nuffield["from"] = "nuffield"
nuffield["type"] = "think_tank"

fft["from"] = "fft"
fft["type"] = "ed_res_org"

fed["from"] = "fed"
fed["type"] = "prof_body"

schoolsweek["from"] = "schoolsweek"
schoolsweek["type"] = "ed_journalism"

gov["from"] = "gov"
gov["type"] = "government"

In [6]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print("from:", df["from"].unique())
    print("type:", df["type"].unique())

📄 EPI
from: ['epi']
type: ['think_tank']

📄 FED
from: ['fed']
type: ['prof_body']

📄 FFT
from: ['fft']
type: ['ed_res_org']

📄 GOV
from: ['gov']
type: ['government']

📄 NUFFIELD
from: ['nuffield']
type: ['think_tank']

📄 SCHOOLSWEEK
from: ['schoolsweek']
type: ['ed_journalism']

In [7]:
for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print(df[["url", "title", "date", "text"]].isna().sum())

📄 EPI
url      0
title    0
date     0
text     0
dtype: int64

📄 FED
url      0
title    0
date     0
text     2
dtype: int64

📄 FFT
url      0
title    0
date     0
text     0
dtype: int64

📄 GOV
url      0
title    0
date     0
text     0
dtype: int64

📄 NUFFIELD
url      0
title    0
date     0
text     0
dtype: int64

📄 SCHOOLSWEEK
url      0
title    0
date     0
text     0
dtype: int64

In [8]:
fed[fed["text"].isna()][["url", "title", "date"]]

,url,title,date
97,https://fed.education/fed-national-education-s...,FED National Education Summit 2023 Speaker Bio...,2023-06-16
98,https://fed.education/fed-national-education-s...,FED National Education Summit 2023 Programme,2023-06-16

In [9]:
#drop rows in fed where text is missing  
fed = fed.dropna(subset=["text"])
fed = fed[fed["text"].str.strip() != ""]

In [10]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

In [11]:
for name, df in datasets.items():
    print(name, df.columns.tolist())

epi ['url', 'title', 'date', 'text', 'from', 'type']
fed ['url', 'title', 'date', 'text', 'from', 'type']
fft ['url', 'title', 'date', 'text', 'from', 'type']
gov ['url', 'title', 'from', 'date', 'text', 'type']
nuffield ['url', 'title', 'date', 'text', 'from', 'type']
schoolsweek ['url', 'title', 'date', 'text', 'from', 'type']

In [12]:
# Change format of schoolsweek date

In [13]:
schoolsweek["date"] = schoolsweek["date"].astype(str).str.split(" ").str[0]

In [14]:
schoolsweek["date"] = pd.to_datetime(
    schoolsweek["date"],
    format="%Y-%m-%d",
    errors="raise"
)

In [15]:
schoolsweek["date"].isna().sum()

np.int64(0)

In [16]:
schoolsweek[["url", "title", "date"]].head(10)

,url,title,date
0,https://schoolsweek.co.uk/schools-lack-resourc...,Schools lack resources to keep pupils with SEN...,2025-12-11
1,https://schoolsweek.co.uk/nightmare-before-chr...,‘Nightmare before Christmas’: 46 free school p...,2025-12-11
2,https://schoolsweek.co.uk/russell-hobby-to-bec...,Russell Hobby to become Labour peer – but will...,2025-12-10
3,https://schoolsweek.co.uk/dfe-dodges-data-tran...,DfE dodges data transparency as it plans new p...,2025-12-08
4,https://schoolsweek.co.uk/ofsted-should-check-...,Ofsted should check SEND funding not plugging ...,2025-12-12
5,https://schoolsweek.co.uk/pupil-premium-income...,Income data to replace free school meals as tr...,2025-12-08
6,https://schoolsweek.co.uk/four-things-we-learn...,Four things we learnt from government data thi...,2025-12-11
7,https://schoolsweek.co.uk/committee-chair-crit...,Committee chair criticises DfE response to SEN...,2025-12-11
8,https://schoolsweek.co.uk/mossbourne-success-o...,Success of top academy achieved ‘at too high a...,2025-12-09
9,https://schoolsweek.co.uk/ofqual-on-screen-ass...,Ofqual: On-screen exams could be introduced by...,2025-12-11

In [17]:
# ensure other datasets are in correct datetime format

In [18]:
for df in [epi, fed, fft, gov, nuffield]:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

# MERGE

In [19]:
cols = ["url", "title", "date", "text", "from", "type"]

epi = epi[cols]
fed = fed[cols]
fft = fft[cols]
gov = gov[cols]
nuffield = nuffield[cols]
schoolsweek = schoolsweek[cols]

In [20]:
full_retro = pd.concat(
    [epi, fed, fft, gov, nuffield, schoolsweek],
    ignore_index=True
)

In [21]:
print("Total rows:", len(full_retro))
print(full_retro["from"].value_counts())
print(full_retro["type"].value_counts())

Total rows: 4331
from
schoolsweek    2742
gov            1061
fft             202
epi             115
nuffield        107
fed             104
Name: count, dtype: int64
type
ed_journalism    2742
government       1061
think_tank        222
ed_res_org        202
prof_body         104
Name: count, dtype: int64

In [22]:
#ensure date is datetime 
full_retro["date"] = pd.to_datetime(full_retro["date"], errors="coerce")

In [23]:
full_retro["date"].min(), full_retro["date"].max()

(Timestamp('2023-01-03 00:00:00'), Timestamp('2025-12-12 00:00:00'))

In [24]:
full_retro.to_csv(
    "/workspaces/ERP_Newsletter/data/data06_full_retrospective/full_retro.csv",
    index=False
)