In [1]:
import pandas as pd

In [2]:
epi = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/epi_articles_2023_2025.csv")
fed = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/fed_news_resources.csv")
fft = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/fft_education_datalab_blog.csv")
gov = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/govuk_education_articles_2023_2025.csv")
nuffield = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/nuffield_articles_2023_2025.csv")
schoolsweek = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/schoolsweek_articles_2023_2025.csv")

In [3]:
schoolsweek.head()

,url,title,date,text
0,https://schoolsweek.co.uk/schools-lack-resourc...,Schools lack resources to keep pupils with SEN...,2025-12-11 05:00,Schools lack resources needed to help keep chi...
1,https://schoolsweek.co.uk/nightmare-before-chr...,‘Nightmare before Christmas’: 46 free school p...,2025-12-11 22:30,Twenty-eight mainstream and 18 special free sc...
2,https://schoolsweek.co.uk/russell-hobby-to-bec...,Russell Hobby to become Labour peer – but will...,2025-12-10 17:25,Academy CEO and former NAHT general secretaryR...
3,https://schoolsweek.co.uk/dfe-dodges-data-tran...,DfE dodges data transparency as it plans new p...,2025-12-08 05:00,The Department for Education (DfE) has refused...
4,https://schoolsweek.co.uk/ofsted-should-check-...,Ofsted should check SEND funding not plugging ...,2025-12-12 09:00,School governing boards are urging Ofsted to e...

In [4]:
gov.head()

,url,title,from,date,text,core_education,primary_org
0,https://www.gov.uk/government/news/uk-italy-yo...,UK-Italy Young Leaders Programme,Department for Business and Trade Italy; Briti...,2024-09-11,English\nItaliano\nApplications for the UK–Ita...,False,Other
1,https://www.gov.uk/government/news/dwp-secreta...,DWP Secretary of State appoints Skills Adviser,Department for Work and Pensions,2026-01-12,An expert adviser has been appointed to suppor...,False,Other
2,https://www.gov.uk/government/publications/not...,Notice to improve: Dorrington Academy Trust,Department for Education,2025-02-28,A notice to improve issued to Dorrington Acade...,True,Department for Education
3,https://www.gov.uk/government/news/government-...,Government to introduce academy trust inspections,Department for Education; The Rt Hon Bridget P...,2026-01-08,New academy trust inspections to boost transpa...,True,Department for Education
4,https://www.gov.uk/government/news/government-...,Government modernises exam records with new app,Department for Education; The Rt Hon Baroness ...,2026-01-08,Every year 11 student in England to be able to...,True,Department for Education

In [5]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

📄 EPI
Rows: 115
Columns: ['url', 'title', 'date', 'text']

📄 FED
Rows: 106
Columns: ['url', 'title', 'date', 'text']

📄 FFT
Rows: 202
Columns: ['url', 'title', 'date', 'text']

📄 GOV
Rows: 1069
Columns: ['url', 'title', 'from', 'date', 'text', 'core_education', 'primary_org']

📄 NUFFIELD
Rows: 107
Columns: ['url', 'title', 'date', 'text']

📄 SCHOOLSWEEK
Rows: 2742
Columns: ['url', 'title', 'date', 'text']

In [6]:
epi["source"] = "epi"
epi["type"] = "think_tank"
epi["institution_name"] = "Education Policy Institute"

nuffield["source"] = "nuffield"
nuffield["type"] = "think_tank"
nuffield["institution_name"] = "Nuffield Foundation"

fft["source"] = "fft"
fft["type"] = "ed_res_org"
fft["institution_name"] = "FFT Education Datalab"

fed["source"] = "fed"
fed["type"] = "prof_body"
fed["institution_name"] = "Foundation for Educational Development"

schoolsweek["source"] = "schoolsweek"
schoolsweek["type"] = "ed_journalism"
schoolsweek["institution_name"] = "Schools Week"

gov["source"] = "gov"
gov["type"] = "government"

## Specific changes to government dataset

In [7]:
# CHANGE: drop non-core education rows FIRST
gov = gov[gov["core_education"] == True].copy()

In [8]:
# CHANGE: government is now a SOURCE CLASS, not an institution
gov["type"] = "gov_inst"

# Preserve the actual publishing body
gov["institution_name"] = gov["source"]

In [9]:
gov = gov.drop(columns=["from", "core_education"])

In [10]:
gov["institution_name"] = gov["primary_org"]

In [11]:
gov = gov.drop(columns=["primary_org"])

## Continue

In [12]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print("source:", df["source"].unique())
    print("type:", df["type"].unique())

📄 EPI
source: ['epi']
type: ['think_tank']

📄 FED
source: ['fed']
type: ['prof_body']

📄 FFT
source: ['fft']
type: ['ed_res_org']

📄 GOV
source: ['gov']
type: ['gov_inst']

📄 NUFFIELD
source: ['nuffield']
type: ['think_tank']

📄 SCHOOLSWEEK
source: ['schoolsweek']
type: ['ed_journalism']

In [13]:
for name, df in datasets.items():
    print(f"\n📄 {name.upper()}")
    print(df[["url", "title", "date", "text"]].isna().sum())

📄 EPI
url      0
title    0
date     0
text     0
dtype: int64

📄 FED
url      0
title    0
date     0
text     2
dtype: int64

📄 FFT
url      0
title    0
date     0
text     0
dtype: int64

📄 GOV
url      0
title    0
date     0
text     0
dtype: int64

📄 NUFFIELD
url      0
title    0
date     0
text     0
dtype: int64

📄 SCHOOLSWEEK
url      0
title    0
date     0
text     0
dtype: int64

In [14]:
fed[fed["text"].isna()][["url", "title", "date"]]

,url,title,date
97,https://fed.education/fed-national-education-s...,FED National Education Summit 2023 Speaker Bio...,2023-06-16
98,https://fed.education/fed-national-education-s...,FED National Education Summit 2023 Programme,2023-06-16

## Drop rows where FED is missing

In [15]:
#drop rows in fed where text is missing  
fed = fed.dropna(subset=["text"])
fed = fed[fed["text"].str.strip() != ""]

## Continue

In [16]:
datasets = {
    "epi": epi,
    "fed": fed,
    "fft": fft,
    "gov": gov,
    "nuffield": nuffield,
    "schoolsweek": schoolsweek,
}

In [17]:
for name, df in datasets.items():
    print(name, df.columns.tolist())

epi ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']
fed ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']
fft ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']
gov ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']
nuffield ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']
schoolsweek ['url', 'title', 'date', 'text', 'source', 'type', 'institution_name']

In [18]:
schoolsweek.head()

,url,title,date,text,source,type,institution_name
0,https://schoolsweek.co.uk/schools-lack-resourc...,Schools lack resources to keep pupils with SEN...,2025-12-11 05:00,Schools lack resources needed to help keep chi...,schoolsweek,ed_journalism,Schools Week
1,https://schoolsweek.co.uk/nightmare-before-chr...,‘Nightmare before Christmas’: 46 free school p...,2025-12-11 22:30,Twenty-eight mainstream and 18 special free sc...,schoolsweek,ed_journalism,Schools Week
2,https://schoolsweek.co.uk/russell-hobby-to-bec...,Russell Hobby to become Labour peer – but will...,2025-12-10 17:25,Academy CEO and former NAHT general secretaryR...,schoolsweek,ed_journalism,Schools Week
3,https://schoolsweek.co.uk/dfe-dodges-data-tran...,DfE dodges data transparency as it plans new p...,2025-12-08 05:00,The Department for Education (DfE) has refused...,schoolsweek,ed_journalism,Schools Week
4,https://schoolsweek.co.uk/ofsted-should-check-...,Ofsted should check SEND funding not plugging ...,2025-12-12 09:00,School governing boards are urging Ofsted to e...,schoolsweek,ed_journalism,Schools Week

In [19]:
gov.head(20)

,url,title,date,text,source,type,institution_name
2,https://www.gov.uk/government/publications/not...,Notice to improve: Dorrington Academy Trust,2025-02-28,A notice to improve issued to Dorrington Acade...,gov,gov_inst,Department for Education
3,https://www.gov.uk/government/news/government-...,Government to introduce academy trust inspections,2026-01-08,New academy trust inspections to boost transpa...,gov,gov_inst,Department for Education
4,https://www.gov.uk/government/news/government-...,Government modernises exam records with new app,2026-01-08,Every year 11 student in England to be able to...,gov,gov_inst,Department for Education
6,https://www.gov.uk/government/publications/dfe...,DfE update 7 January 2026,2026-01-07,Latest information and actions from the Depart...,gov,gov_inst,Department for Education
8,https://www.gov.uk/government/publications/dfe...,DfE update 17 December 2025,2025-12-17,Latest information and actions from the Depart...,gov,gov_inst,Department for Education
10,https://www.gov.uk/government/news/ofqual-fine...,Ofqual fines Pearson £2 million for rule breac...,2025-12-15,Exam board issued more than £2 million in comb...,gov,gov_inst,Ofqual
11,https://www.gov.uk/government/news/major-expan...,Major expansion of colleges to train next gene...,2025-12-15,Local colleges set to receive £570 million to ...,gov,gov_inst,Department for Education
12,https://www.gov.uk/government/publications/not...,Notice to improve: Mercian Educational Trust,2025-12-12,A notice to improve issued to Mercian Educatio...,gov,gov_inst,Department for Education
13,https://www.gov.uk/government/publications/not...,Notice to improve: Sikh Academies Trust,2024-11-15,A notice to improve issued to Sikh Academies T...,gov,gov_inst,Department for Education
14,https://www.gov.uk/government/news/new-qualifi...,New qualifications to tackle NHS skills shortage,2025-12-12,"New qualifications in MedTech to tackle 145,00...",gov,gov_inst,Skills England
15,https://www.gov.uk/government/publications/res...,Response to Secretary of State steer letter,2025-12-11,A letter to the Secretary of State from Sir Ia...,gov,gov_inst,Ofqual
16,https://www.gov.uk/government/publications/on-...,On-screen exams: Education Secretary writes to...,2025-12-11,"Education Secretary, Bridget Phillipson, write...",gov,gov_inst,Department for Education
17,https://www.gov.uk/government/news/support-for...,Support for children with SEND who are not in ...,2025-12-11,A report by Ofsted and the Care Quality Commis...,gov,gov_inst,Ofsted
18,https://www.gov.uk/government/news/ofqual-laun...,Ofqual launches consultation to protect standa...,2025-12-11,Ofqual is today launching a 12-week public con...,gov,gov_inst,Ofqual
19,https://www.gov.uk/government/news/3bn-investm...,£3bn investment to end postcode lottery for ch...,2025-12-11,"Around 50,000 specialist places to be created ...",gov,gov_inst,Department for Education
21,https://www.gov.uk/government/publications/dfe...,DfE update 10 December 2025,2025-12-10,Latest information and actions from the Depart...,gov,gov_inst,Department for Education
24,https://www.gov.uk/government/publications/let...,Letter to higher education providers: 9 Decemb...,2025-12-09,Letter from the Secretary of State for Educati...,gov,gov_inst,Department for Education
25,https://www.gov.uk/government/news/government-...,Government crackdown on rogue university franc...,2025-12-09,Education Secretary announces reforms to tight...,gov,gov_inst,Department for Education
26,https://www.gov.uk/government/news/schools-to-...,Schools to save millions as Government launche...,2025-12-04,New programme launched to help schools tackle ...,gov,gov_inst,Department for Education
27,https://www.gov.uk/government/news/more-people...,More people training to teach,2025-12-04,Trainee teacher numbers reach highest point si...,gov,gov_inst,Department for Education

In [20]:
# Change format of schoolsweek date

In [21]:
schoolsweek["date"] = schoolsweek["date"].astype(str).str.split(" ").str[0]

In [22]:
schoolsweek["date"] = pd.to_datetime(
    schoolsweek["date"],
    format="%Y-%m-%d",
    errors="raise"
)

In [23]:
schoolsweek["date"].isna().sum()

np.int64(0)

In [24]:
schoolsweek[["url", "title", "date"]].head(10)

,url,title,date
0,https://schoolsweek.co.uk/schools-lack-resourc...,Schools lack resources to keep pupils with SEN...,2025-12-11
1,https://schoolsweek.co.uk/nightmare-before-chr...,‘Nightmare before Christmas’: 46 free school p...,2025-12-11
2,https://schoolsweek.co.uk/russell-hobby-to-bec...,Russell Hobby to become Labour peer – but will...,2025-12-10
3,https://schoolsweek.co.uk/dfe-dodges-data-tran...,DfE dodges data transparency as it plans new p...,2025-12-08
4,https://schoolsweek.co.uk/ofsted-should-check-...,Ofsted should check SEND funding not plugging ...,2025-12-12
5,https://schoolsweek.co.uk/pupil-premium-income...,Income data to replace free school meals as tr...,2025-12-08
6,https://schoolsweek.co.uk/four-things-we-learn...,Four things we learnt from government data thi...,2025-12-11
7,https://schoolsweek.co.uk/committee-chair-crit...,Committee chair criticises DfE response to SEN...,2025-12-11
8,https://schoolsweek.co.uk/mossbourne-success-o...,Success of top academy achieved ‘at too high a...,2025-12-09
9,https://schoolsweek.co.uk/ofqual-on-screen-ass...,Ofqual: On-screen exams could be introduced by...,2025-12-11

In [25]:
# ensure other datasets are in correct datetime format

In [26]:
for df in [epi, fed, fft, gov, nuffield]:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

# MERGE

In [27]:
cols = ["url", "title", "date", "text", "source", "type"]

epi = epi[cols]
fed = fed[cols]
fft = fft[cols]
gov = gov[cols]
nuffield = nuffield[cols]
schoolsweek = schoolsweek[cols]

In [28]:
full_retro = pd.concat(
    [epi, fed, fft, gov, nuffield, schoolsweek],
    ignore_index=True
)

In [29]:
print("Total rows:", len(full_retro))
print(full_retro["source"].value_counts())
print(full_retro["type"].value_counts())

Total rows: 3972
source
schoolsweek    2742
gov             702
fft             202
epi             115
nuffield        107
fed             104
Name: count, dtype: int64
type
ed_journalism    2742
gov_inst          702
think_tank        222
ed_res_org        202
prof_body         104
Name: count, dtype: int64

In [30]:
#ensure date is datetime 
full_retro["date"] = pd.to_datetime(full_retro["date"], errors="coerce")

In [31]:
full_retro["date"].min(), full_retro["date"].max()

(Timestamp('2023-01-03 00:00:00'), Timestamp('2026-01-08 00:00:00'))

In [32]:
full_retro.to_csv(
    "/workspaces/ERP_Newsletter/data/data06_full_retrospective/full_retro.csv",
    index=False
)